### ISSUE TITLE
Main prop is not pointing to the right path

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-redux#6]
In the package.json ``` "main": "dist/sn-redux.js",``` which is not a valid path.
It should be ```./index.js``` or ```dist/src/sn-redux.js```
Please change it.

**Comment by gallayl** [comment]
Fixed in the [following](https://github.com/SenseNet/sn-redux/commit/265dd11618e37a161b53dc08297a06a11d6dfed5) commit
