### ISSUE TITLE
Add redux devtools by default or a way to add that to the createSensenetStore

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-redux#83]
Right now there is no way to add [redux-devtools](https://github.com/zalmoxisus/redux-devtools-extension) to the store.

    const store = createStore(
        options.rootReducer,
        {},
        applyMiddleware(...middlewareArray),
    )

redux-devtools should wrap the `applyMiddleware()` method.

**Comment by herflis** [comment]
#81
