### ISSUE TITLE
Add types to CreateStoreOptions

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-redux#84]
CreateStoreOptions doesn't have types added to the properties. Please add types to them so intelisense can work better.

```
export interface CreateStoreOptions {
    rootReducer,
    repository,
    middlewares?,
    persistedState?
}
```

**Comment by herflis** [comment]
@B3zo0 thanks for the request. It is fixed in version 4.1.0. To check the changes see the [docs](https://community.sensenet.com/api/sn-redux/interfaces/store.createstoreoptions.html)
