### ISSUE TITLE
Loginstate doesn't go to Pending state

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-redux#85]
After `'USER_CHANGED'` the state set to Unauthenticated. After dispatching login from actions `'USER_LOGIN_LOADING'` doesn't change the state to pending. I expect the loginstate to be pending once it is in a loading state.

**Comment by herflis** [comment]
@B3zo0 thanks for the request. It is fixed in [version 4.1.0](https://github.com/SenseNet/sn-redux/blob/5b9956f/src/Reducers.ts#L71)
