### ISSUE TITLE
Reducers ids create content success payload doesn't have result property

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-redux#87]
In [reducers line 210](https://github.com/SenseNet/sn-redux/blob/master/src/Reducers.ts#L210) the action.payload doesn't have a result property.
```
export const createContent = <T extends IContent = IContent>(parentPath: string, content: T, contentType: string) => ({
    type: 'CREATE_CONTENT',
    // tslint:disable:completed-docs
    async payload(repository: Repository): Promise<IODataResponse<T>> {
        const data = await repository.post<T>({ parentPath, content, contentType })
        return data
    },
})
```
Create content returns an IODataResponse.

**Comment by herflis** [comment]
@B3zo0 thanks for the request. It is fixed now in [version 4.1.0](https://github.com/SenseNet/sn-redux/blob/5b9956f/src/Reducers.ts#L217)
